### ISSUE TITLE
Informer@AAAI2021's results

### ISSUE THREAD

**Issue by cuiyuebing** [zhouhaoyi/ETDataset#2]
Hi! May I ask the results presented in the Informer@AAAI2021 paper are based on which dataset (small, large or full)? Thanks!

**Comment by zhouhaoyi** [comment]
Please refer to https://github.com/zhouhaoyi/Informer2020, we have updated all the results with hyperparameter settings. In the Informer paper, we use the small one.

**Comment by cuiyuebing** [comment]
Got it, thanks!
