### ISSUE TITLE
Physical meaning of "HUFL", "HULL", "MUFL", "MULL", "LUFL", "LULL" values?

### ISSUE THREAD

**Issue by nazarovsky** [zhouhaoyi/ETDataset#3]
Could you please elaborate on what are those features in the dataset, and how they were measured?
Are they High/Mean/Low values of active/reactive power delivered to the transformer load over 15 minute period?

**Comment by zhouhaoyi** [comment]
The High/Mean/Low values are the exact transformer load at the record time, not the average load over 15 minutes.  Actually, our device is recorded at the second level, we just pick up 15-min values. And the High value stands for the High input of the transformer, and the next level output is Mean and Low, such that you can always find that High >= Mean + low.

**Comment by nazarovsky** [comment]
So the transformer basically has one primary and two secondary windings,
and you measure HUFL/ HULL, i.e. active/reactive input power on the high
voltage side (HV primary transformer winding). And also you measure output
powers on medium and low voltage side (secondary medium voltage and
secondary low voltage windings)? And the oil temperature correlates with
the power losses in transformer. That makes sense, thank you!

**Comment by elesun2018** [comment]
懂了一些，感谢，能否再推荐一下相关资料，比如：搜索关键词 知识点链接 等等。谢谢

**Comment by haozhenHG** [comment]
数据集以CSV格式存储，第一行为数据头，包括
高有效负载（HUFL）、高无效负载（HULL）、中有效负载（MUFL）、中无效负载（MULL）、低有效负载（LUFL）、低无效负载（LULL）、油温（OT）
