### ISSUE TITLE
is:issue is:open large和full数据集是还未上传还是尚未收集完成啊 

### ISSUE THREAD

**Issue by chenshimao** [zhouhaoyi/ETDataset#4]

**Comment by zhouhaoyi** [comment]
欢迎关注我们的数据集。目前我们还在积极和数据源公司争取，能尽快公开数据集。数据采集工作基本完成，但是开放数据集可能需要更长的时间。希望能理解我们的难处，稍作等待。

**Comment by 929220967** [comment]
有没有完整的数据集，比如ETT-full：含有69个电力变压器（来自39个站点）的数据，包括负载、油温、位置、气候、需求。这个

**Comment by zhouhaoyi** [comment]
> 有没有完整的数据集，比如ETT-full：含有69个电力变压器（来自39个站点）的数据，包括负载、油温、位置、气候、需求。这个

请参考上面的回答。这个数据集还在处理中。
